image: elixir:1.5.3-alpine

pipelines:
  default:
    - step:
        script:
          - mix local.hex --force
          - mix local.rebar --force
          - mix deps.get
          - mix compile
          - mix test

